all:
	make exo1
	make exo2
	make exo3

exo1: exo1.c
	gcc -o exo1 exo1.c -Wall -ansi

exo2: exo2.c
	gcc -o exo2 exo2.c -Wall -ansi

exo3: exo3.c
	gcc -o exo3 exo3.c -Wall -ansi

clean:
	rm exo1
	rm exo2
	rm exo3
