all:
	make exo1
	make exo2
	make exo3
	make exo4
	make exo5

exo1: exo1.c
	gcc -o exo1 exo1.c -Wall -ansi

exo2: exo2.c
	gcc -o exo2 exo2.c -Wall -ansi

exo3: exo3.c
	gcc -o exo3 exo3.c -Wall -ansi

exo4: exo4.c
	gcc -o exo4 exo4.c -Wall -ansi

exo5: exo5.c
	gcc -o exo5 exo5.c -Wall -ansi

clean:
	rm exo1
	rm exo2
	rm exo3
	rm exo4
	rm exo5
